syntax = "proto3";

option csharp_namespace = "VSpark.Protos";

import "google/protobuf/empty.proto";

service IncidentService {
  rpc CreateIncidentAsync (CreateIncidentRequest) returns (CreateIncidentResponse);

  rpc UploadIncidentArtifact (stream UploadIncidentArtifactRequest) returns (google.protobuf.Empty);
}

enum IncidentType {
	INCIDENT_TYPE_UNSPECIFIED = 0;
	INCIDENT_TYPE_PPE = 1;
	INCIDENT_TYPE_TRAUMA = 2;
	INCIDENT_TYPE_SMOKING = 3;
}

enum IncidentPriority {
	INCIDENT_PRIORITY_STANDART = 0;
	INCIDENT_PRIORITY_WARNING = 1;
	INCIDENT_PRIORITY_CRITICAL = 2;
}

enum IncidentStatus {
	INCIDENT_STATUS_ACTIVE = 0;
	INCIDENT_STATUS_INREVIEW = 1;
	INCIDENT_STATUS_CLOSED = 2;
	INCIDENT_STATUS_ESCALATED = 3;
}

message CreateIncidentRequest {
  string description = 1; 
  int32 type = 2; 
  string reporter_id = 3;
  string severity = 4;
}

message UploadIncidentArtifactRequest {
	oneof data {
		string guid = 1;
		bytes file = 2;
	}
}

message CreateIncidentResponse {
  string incident_id = 1;
  string status = 2;
  string created_at = 3;
}

message UpdateIncidentRequest {
	int32 Priority = 1;
	int32 Status = 2;
}